// Comprehensive list of CDMX and Metropolitan Area zones (West, North, South, Central) including Atizapán de Zaragoza, Naucalpan, Huixquilucan, etc.
export const COMPREHENSIVE_ZONES = [
  // Zona Poniente / Metropolitana Oeste
  'Interlomas',
  'Atizapán de Zaragoza',
  'Naucalpan',
  'Huixquilucan',
  'Santa Fe',
  'Bosques de las Lomas',
  'Tecamachalco',
  'La Herradura',
  'Bosque Real',
  'Jesús del Monte',
  'Lomas Anáhuac',
  'Vista Hermosa',
  'Contadero',
  'Cuajimalpa',
  'Lomas de Bezares',
  'Lomas Verdes',
  'Ciudad Satélite',
  'Satélite',
  'Echegaray',
  'Valle Dorado',
  'Arboledas',
  'Paseos de la Herradura',
  
  // Polanco & Lomas CDMX
  'Polanco',
  'Polanco I Secc',
  'Polanco II Secc',
  'Polanco III Secc',
  'Polanco IV Secc',
  'Polanco V Secc',
  'Lomas de Chapultepec',
  'Anzures',
  'Granada',
  'Ampliación Granada (Nuevo Polanco)',
  'Chapultepec',
  
  // Zona Centro / Condesa / Roma
  'Condesa',
  'Hipódromo Condesa',
  'Roma Norte',
  'Roma Sur',
  'Juárez',
  'Cuauhtémoc',
  'San Rafael',
  'Santa María la Ribera',
  'Escandón',
  'San Miguel Chapultepec',
  
  // Zona Sur / Del Valle / Coyoacán / Pedregal
  'Del Valle',
  'Narvarte',
  'Nápoles',
  'San Borja',
  'Insurgentes Mixcoac',
  'San Pedro de los Pinos',
  'Pedregal',
  'Jardines del Pedregal',
  'San Ángel',
  'San Ángel Inn',
  'Chimalistac',
  'Coyoacán',
  'Villa Coyoacán',
  'Del Carmen',
  'San Diego Churubusco',
  'Parque San Andrés',
  'Insurgentes Cuicuilco',
  'Tlalpan',
  'San Jerónimo'
];
